### ISSUE TITLE
Matchers should be able to return rich error info in case of errors

### ISSUE THREAD

**Issue by krzkaczor** [l2beat/earl#114]
Related: https://github.com/earl-js/earl/pull/113#discussion_r543428304

Probably error messages should be moved from validators to matchers too. This way we will get with super simple way to create validators for existing matchers and matchers will be able to return richer errors in case of mismatch.

**Comment by sz-piotr** [comment]
I'm closing this issue, since error messages have improved greatly since 2020. We'll of course be revisiting them more, but in an unrelated, more global approach
