### ISSUE TITLE
Add support for TypeScript's Assertion Functions

### ISSUE THREAD

**Issue by rustyconover** [l2beat/earl#130]
One of Jest's weaknesses is that it doesn't use assertion functions based on the matchers.

See:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/41179

**Comment by krzkaczor** [comment]
I investigated it in the past. Currently, assertion functions are quite fragile (ie they don't work as part of the objects etc), which makes them impossible to utilize with the current API.
