### ISSUE TITLE
All basic matchers should have corresponding validators

### ISSUE THREAD

**Issue by krzkaczor** [l2beat/earl#147]
For example we have:
expect.stringMatching(...)  but not expect().toBeAStringMatching(...)

**Comment by hasparus** [comment]
Do you want to preserve a strict naming scheme like `expect().toBeXXX()` based on `expect.XXX()` or should we possibly try to make them more concise (e.g. `expect(actual).toMatch(pattern))`?

**Comment by krzkaczor** [comment]
I think we should be consistent. So if we want to change the naming for validator we should rename matcher to. 

I like `stringMatching` b/c it's obvious what it does and with what types it works. And we already have bunch of patterns names like this: `toBeAContainerWith(...expectedItems)`

**Comment by sz-piotr** [comment]
Closing this as this is exactly what we are doing for v0.3
