### ISSUE TITLE
Expose isEqual options to the user

### ISSUE THREAD

**Issue by hasparus** [l2beat/earl#171]
See https://github.com/dethcrypto/earl/pull/165#discussion_r784140229.

Currently, the options documented in https://earljs.dev/docs/advanced/equality-algorithm#algorithm are not exposed to the user. While I personally wouldn't set `uniqueNaNs` or `minusZero` to true, some advanced Earl users might need it, especially when migrating from other assertion libraries.

**Comment by sz-piotr** [comment]
Closing this as this is not in scope for the foreseeable future. The options are available if the user wishes to call `toEqual` directly, but otherwise we prefer to keep the matchers simple.

**Comment by DGCK81LNN** [comment]
I need to ensure my functions yield zeroes with the corrent signs in one of my recent projects. Looks like I'll need to write my own matcher.
