### ISSUE TITLE
TS2589: Type instantiation is excessively deep and possibly infinite when recursive type is given to `toEqual`

### ISSUE THREAD

**Issue by hasparus** [l2beat/earl#172]
Given recursive type `toEqual` fails with `TS2589`.

```ts
import { expect } from 'earljs'

export type json =
  | string
  | number
  | boolean
  | null
  | json[]
  | { [key: string]: json }

const actual: json = {}

expect(actual).toEqual({})
```

[**See TypeScript Playground**](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUwB5mQY3gXzgMyghDgHJkBDKAGwCsBnUgWAChW1JY4YBPDOBhAB2cALys4cAD5x6MKMCEBzCdLhCAriABGyKKpnaIEapSEH1G6tQuChAbQC6FpPYDWyHgC5Z8xUscfOzgcVlZMYTk4CmwNCmog+mExRFC2Fg4sGAAKGJg46gBKADoYCABRAEcC7IQcQqA)

**Comment by sz-piotr** [comment]
@krzkaczor any progress on this?

**Comment by sz-piotr** [comment]
The newest development version does away with the ability to override type checking via smart equality rules and so the type is now just `T` which works for recursive types.
