### ISSUE TITLE
setTestRunnerIntegration is not exported from top level

### ISSUE THREAD

**Issue by andrew0** [l2beat/earl#176]
I'm trying to use earl with [uvu](https://github.com/lukeed/uvu) for its snapshot capabilities, but it seems like the `setTestRunnerIntegration` is not exported from the package entrypoint, so I have to require `earljs/dist/testRunnerCtx` directly. Is this meant to be public API? If so, I think it would be better to export it from the index.

**Comment by krzkaczor** [comment]
I initially thought that it shouldn't be easily accessible but we would rather add first-class support for other test runners. 

@andrew0 feel free to add a PR with uvu support. Similiar to mocha: https://github.com/dethcrypto/earl/blob/master/packages/earljs/src/test-runners/mocha.ts

**Comment by sz-piotr** [comment]
This style of doing test runner support is being removed in v0.3 in favor of having no special configuration required.
