### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by m-ronchi** [l2beat/earl#180]
running `npm i earljs` on an empty project yields
```
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
```

those packages come from
```
$ npm ls source-map-url urix resolve-url source-map-resolve sane
└─┬ earljs@0.2.1
  └─┬ jest-snapshot@26.6.2
    └─┬ jest-haste-map@26.6.2
      └─┬ sane@4.1.0
        └─┬ micromatch@3.1.10
          └─┬ snapdragon@0.8.2
            └─┬ source-map-resolve@0.5.3
              ├── resolve-url@0.2.1
              ├── source-map-url@0.4.1
              └── urix@0.1.0
```
you should at least update `jest-snapshot` to ^27 (released 9 months ago) (if you won't address #106 )
then preferably setup some dependency bot like [renovate](https://github.com/marketplace/renovate) and/or [dependabot](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-dependabot-security-updates)

**Comment by sz-piotr** [comment]
The newest development version completely removes `jest-snapshot`.

The changes are going to be released soon!
