### ISSUE TITLE
way of and-ing or or-ing matchers together

### ISSUE THREAD

**Issue by joelwestland** [l2beat/earl#196]
It would be very useful to have a way of combining two matchers by requiring that either or both be true, and increase the flexibility of the library.

**Comment by sz-piotr** [comment]
At the moment this isn't something that we plan to support - we'd essentially be turning `earl` into a more constrained `zod`. The newest development version however includes two matchers that make adding custom logic really easy:

1. `expect.check(predicate)`
2. `expect.schema(ZodSchema)`

The changes are going to be released soon.
