### ISSUE TITLE
Make easier to extend earljs within project

### ISSUE THREAD

**Issue by joelwestland** [l2beat/earl#197]
**revised after trying out plugin system**

Right now if there is a missing matcher, validator, etc in earljs the only way to extend it is using a plugin, a process which seems to be intended for those developing plugins meant to be published publicly. If one needs a very simple extra matcher (like #195) then they have to write a ton of boilerplate for it. Either plugin creation should be easier or there should be a simpler way of extending earl within a single project without needing a whole plugin. 

An easy way of doing this, for example, would be adding a matcher `expect.customMatcher` that takes a user-provided `Matcher` class.

**Comment by sz-piotr** [comment]
The newest development version includes a number of improvements to the process of extending earl with custom matchers and validators.

See: https://github.com/l2beat/earl/blob/fd4420e281b632dd8762d425efb476742d98844a/.changeset/odd-buckets-tell.md

And: https://github.com/l2beat/earl/blob/fd4420e281b632dd8762d425efb476742d98844a/packages/earljs/src/matchers/check.ts

We expect the changes to be released soon.
