### ISSUE TITLE
Current plan for validators in 0.3.x

### ISSUE THREAD

**Issue by sz-piotr** [l2beat/earl#226]
```
// modifiers
not
promise

// equality
toEqual(value)
toEqualLoose(value) - .loose (!)
toEqualExactly(value) - .exactly (!) - use same value zero
toEqualUnordered(array) - .unordered (!)

// other
toBeTruthy() - .truthy
toBeFalsy() - .falsy
toBeDefined() - .defined (!)
toBeNullish() - .nullish, .notNullish (!)
toBeA(class) - .a
toMatchRegex(regex) - .regex
toSatisfy(predicate) - .satisfies (!)

// containers
toHaveProperty(key, value?) - .property (!)
toHaveSubset(subset) - .subset (!)
toHaveLength(length) - .length
toInclude(...items) - .includes (!) - replaces substring for strings
toBeEmpty() - .empty, .notEmpty (!)

// snapshot
toMatchSnapshot(context)

// errors
toThrow(message?)
toThrow(class, message?)
toThrowMatchingSnapshot()

// numbers
toBeCloseTo(target, precision) - .closeTo
toBeGreaterThan(target) - .greaterThan
toBeGreaterThanOrEqual(target) - .greaterThanOrEqual
toBeLessThan(target) - .lessThan
toBeLessThanOrEqual(target) - .lessThanOrEqual

// mocks
toBeExhausted()
toHaveBeenCalled()
toHaveBeenCalledTimes(count)
toHaveBeenCalledWith(...args)
toHaveBeenCalledOnlyWith(...args)
toHaveBeenLastCalledWith(...args)
toHaveBeenNthCalledWith(time, ...args)
```

**Comment by alcuadrado** [comment]
Can we please move snapshot tests to a plugin and make earl 0-dep? 🤞

Also, one of the things I found more confusing about earl when I first tried it is `toEqual`'s name, as it's more of a pattern matching operation.

**Comment by krzkaczor** [comment]
> Can we please move snapshot tests to a plugin and make earl 0-dep? 🤞

@alcuadrado, @sz-piotr decided to reimplement snapshots in a way that they don't rely on jest (and avoid downloading half of npm as dependencies). So this should be solved. More info: https://github.com/l2beat/earl/issues/106#issuecomment-1465282624

> Also, one of the things I found more confusing about earl when I first tried it is toEqual's name, as it's more of a pattern matching operation.

Hmm right I can see your point but basically, in earl, matchers are supported everywhere, including `toEqual`. This is I believe very similar to what for example jest does: https://jestjs.io/docs/expect#expectarraycontainingarray

**Comment by alcuadrado** [comment]
yeah, i know that, but maybe using something like `toMatch(matcher)` as the "default" function?

**Comment by alcuadrado** [comment]
> @alcuadrado Can you elaborate on what you would like to see a bit more? I don't think I fully understand your concerns.

It's more of an English concern than a technical one. Some examples read weird in English, like `expect('abc').toEqual(expect.a(String))`

**Comment by alcuadrado** [comment]
> are equally weird?

They are less weird. I see your point.

> while `expect('abc').toEqual(expect.a(String))` is a possibility that we will recommend against.

I took that from the docs

**Comment by sz-piotr** [comment]
Closing this issue as we're getting close to 1.0 release and do not plan any more features at this time.
