### ISSUE TITLE
Use bundler like tsup

### ISSUE THREAD

**Issue by krzkaczor** [l2beat/earl#256]
By leveraging a simple bundler we could make this package dependency free for end users speeding up installation times:

https://tsup.egoist.dev

**Comment by sz-piotr** [comment]
That seems like a nice idea, however the current state of the library is really lightweight.
Here's a complete list of dependencies and sub-dependencies:
```
earljs
- error-stack-parser
  - stackframe
```

Is bundling really worth it, especially considering that those packages can get independent security updates?

**Comment by sz-piotr** [comment]
Decided as not worth it
