### ISSUE TITLE
RFC: Earl test utils

### ISSUE THREAD

**Issue by krzkaczor** [l2beat/earl#68]
Should earl (or should we develop `earljs-utils` package) ship with generic test utils?

Utils like:
- clear node module cache - useful for testing modules with state

- ignore files with certain extensions - useful when testing webpack-loadable code with mocha (example: `import "styles.css"`

- fixture helpers factory - I often use fixture factory function in my tests that allows reusing fixture with small changes between tests

And probably some more...

**Comment by krzkaczor** [comment]
Another good util: `nock` helper to automatically record / replay fixtures.

**Comment by sz-piotr** [comment]
Closing this as for the foreseeable future we aren't planning to develop this.
