### ISSUE TITLE
RFC: Self hosting

### ISSUE THREAD

**Issue by sz-piotr** [l2beat/earl#73]
Should earl be tested using an earlier, stable version of earl? This would enable dropping the dependency on the chai+friends combo.

**Comment by krzkaczor** [comment]
Yeah yeah, it should be. But let's don't rush about it. @LogvinovLeon did it here: https://github.com/earl-js/earl/pull/51 and it was masking some bugs 😨  so i reverted it after all (it was also before a stable release).

Now I have quite strong opinions on this topic:
1. Let's don't rush the migration. Maybe we don't have to wait till `1.0.0` but let's wait a couple of weeks more. Believe me - I would really love to get rid of chai and tens of other deps but it's not yet time for it.

2. We should NOT use earl from this repository but rather version hosted from npm. I am not sure how to achieve it in another way than publishing earl under a different name. 

Using earl from this repository to test earl from this repository will make debugging harder and generally reduce confidence in tests (what if earl suddenly stops throwing any errors? - all tests would pass).

**Comment by sz-piotr** [comment]
with 2. you just specify a version that is not in the repo i think

**Comment by krzkaczor** [comment]
> with 2. you just specify a version that is not in the repo i think

tried it - didn't work.

**Comment by sz-piotr** [comment]
Closing this as for the foreseeable future we aren't planning to do that.
